### ISSUE TITLE
[Bug] [JDBC] column "id" is of type uuid but expression is of type character varying

### ISSUE THREAD

**Issue by x956606865** [InterestingLab/seatunnel#712]
### Search before asking

- [X] I had searched in the [issues](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I just use jdbc plugin to read table data from my prod database and use jdbc to write data to my dev database, but I get this issue:

`java.sql.BatchUpdateException: Batch entry 0 INSERT INTO cnb."Values" ("id","createdAt","updatedAt","deletedAt","name","order","category","lastName","parentId","_ide_status","_ide_script_status") VALUES ('6774d596-8cc8-4c20-8e98-6f2f105d62a8','2021-07-06 16:52:37.477347+08','2021-07-06 16:54:41.764082+08','2021-07-06 16:54:41.764082+08','Test Value',0,'LicenseSubType',NULL,NULL,'normal','normal') was aborted: ERROR: column "id" is of type uuid but expression is of type character varying
`

The sql is right, but why it not execute it, and throw this error?

### SeaTunnel Version

1.5.5

### SeaTunnel Config

```conf
spark {
  spark.streaming.batchDuration = 5
  spark.app.name = "seatunnel"
  spark.ui.port = 13000
}

input {
       jdbc {
		driver = "org.postgresql.Driver"
		url = "jdbc:postgresql://xxx/postgres?useUnicode=true&charSet=utf8&autoReconnect=true"
		
		#数据库链接用户名及密码
		user = "xxx"
		password = "xxxxx"
		table = "cnb.\"Values\""
		result_table_name = "xxx"
		jdbc.fetchsize = 100
	}

}

filter {
}

output {
jdbc {
    driver = "org.postgresql.Driver"
    url = "jdbc:postgresql://xxx2?useUnicode=true&charSet=utf8&autoReconnect=true"
   table = "cnb.\"Values\""
    user = "xxx"
    password = "xxx"
}
}
```

### Running Command

```shell
../bin/start-seatunnel.sh --master local --deploy-mode client --config ./test.conf
```

### Error Exception

```log
2021-11-25 20:43:09 ERROR Executor:91 - Exception in task 0.0 in stage 0.0 (TID 0)
java.sql.BatchUpdateException: Batch entry 0 INSERT INTO cnb."Values" ("id","createdAt","updatedAt","deletedAt","name","order","category","lastName","parentId","_ide_status","_ide_script_status") VALUES ('6774d596-8cc8-4c20-8e98-6f2f105d62a8','2021-07-06 16:52:37.477347+08','2021-07-06 16:54:41.764082+08','2021-07-06 16:54:41.764082+08','Test Value',0,'LicenseSubType',NULL,NULL,'normal','normal') was aborted: ERROR: column "id" is of type uuid but expression is of type character varying
  建议：You will need to rewrite or cast the expression.
  位置：160  Call getNextException to see other errors in the batch.
        at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:169)
        at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:862)
        at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:901)
        at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1644)
        at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:676)
        at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$$anonfun$saveTable$1.apply(JdbcUtils.scala:838)
        at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$$anonfun$saveTable$1.apply(JdbcUtils.scala:838)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:980)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:980)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2107)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2107)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:123)
        at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:411)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:417)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

### Flink or Spark Version

spark 2.4.8

### Java or Scala Version

1.8.0_292

### Screenshots

![image](https://user-images.githubusercontent.com/10432052/143444927-a96b7394-d2f4-433b-921e-438e347c7e19.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by RickyHuo** [comment]
Could you show the schema of cnb.Values ? @x956606865

**Comment by x956606865** [comment]
@RickyHuo
This is my table DDL:
`
CREATE TABLE "cnb"."Values" (
  "_ide_status" varchar COLLATE "pg_catalog"."default" DEFAULT 'normal'::character varying,
  "_ide_script_status" varchar COLLATE "pg_catalog"."default" DEFAULT 'normal'::character varying,
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "createdAt" timestamptz(6) DEFAULT now(),
  "updatedAt" timestamptz(6) DEFAULT now(),
  "deletedAt" timestamptz(6),
  "name" text COLLATE "pg_catalog"."default",
  "order" int4,
  "category" text COLLATE "pg_catalog"."default",
  "lastName" text COLLATE "pg_catalog"."default",
  "parentId" uuid,
  CONSTRAINT "PK_20911d8fe3d2273d60c489da8c9" PRIMARY KEY ("id"),
  CONSTRAINT "FK_b27091a97b65d4360e475444a6b" FOREIGN KEY ("parentId") REFERENCES "cnb"."Values" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
)
;
`
I just use the id column as primary key, the type is uuid.

but in error report ,the sql it right,why it not execute,but throw a error? 
`INSERT INTO cnb."Values" ("id","createdAt","updatedAt","deletedAt","name","order","category","lastName","parentId","_ide_status","_ide_script_status") VALUES ('6774d596-8cc8-4c20-8e98-6f2f105d62a8','2021-07-06 16:52:37.477347+08','2021-07-06 16:54:41.764082+08','2021-07-06 16:54:41.764082+08','Test Value',0,'LicenseSubType',NULL,NULL,'normal','normal')`

**Comment by RickyHuo** [comment]
@x956606865 It seem that uuid column can't insert a specify value.

**Comment by x956606865** [comment]
@RickyHuo
But if I run the sql in db, it can insert data successfully....
`INSERT INTO cnb."Values" ("id","createdAt","updatedAt","deletedAt","name","order","category","lastName","parentId","_ide_status","_ide_script_status") VALUES ('6774d596-8cc8-4c20-8e98-6f2f105d62a8','2021-07-06 16:52:37.477347+08','2021-07-06 16:54:41.764082+08','2021-07-06 16:54:41.764082+08','Test Value',0,'LicenseSubType',NULL,NULL,'normal','normal')`

**Comment by RickyHuo** [comment]
According to 

> https://stackoverflow.com/questions/66363284/column-is-of-type-uuid-but-expression-is-of-type-character-varying-in-spark-scal

Add `stringtype=unspecified` in you jdbc url

@x956606865

**Comment by x956606865** [comment]
@RickyHuo
Oh~ Thanks
