### ISSUE TITLE
[Bug] [Module Name] Kudu2ClickHouse Timestamp type error

### ISSUE THREAD

**Issue by Shmilyqjj** [InterestingLab/seatunnel#848]
### Search before asking

- [X] I had searched in the [issues](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

when i extract data from kudu 1.10.0 to clickhouse 21.x, kudu timestamp cloumn failed.（java.lang.ClassCastException: java.sql.Timestamp cannot be cast to java.lang.String
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse.renderBaseTypeStatement(Clickhouse.scala:351)）

Kudu timestamp column can not cast to clickhouse column type.Then executor throw "job aborted".

Kudu Table
+-----------------+-----------+---------+-------------+----------+---------------+---------------+---------------------+------------+
| name            | type      | comment | primary_key | nullable | default_value | encoding      | compression         | block_size |
+-----------------+-----------+---------+-------------+----------+---------------+---------------+---------------------+------------+
| cust_no         | string    |         | true        | false    |               | AUTO_ENCODING | DEFAULT_COMPRESSION | 0          |
| tag_code        | string    |         | true        | false    |               | AUTO_ENCODING | DEFAULT_COMPRESSION | 0          |
| update_datetime | timestamp |         | false       | true     |               | AUTO_ENCODING | DEFAULT_COMPRESSION | 0          |
+-----------------+-----------+---------+-------------+----------+---------------+---------------+---------------------+------------+

CH Table
CREATE TABLE test.k_tag_sb
(
    `cust_no` String,
    `tag_code` String,
    `update_datetime` Date
)
ENGINE = MergeTree
ORDER BY cust_no;

### SeaTunnel Version

1.5.5

### SeaTunnel Config

```conf
# File: /opt/seatunnel-1.5.5/config/kudu2ch.batch.all.conf
spark {
  spark.app.name = "kudu2ch"
  spark.executor.instances = 2
  spark.executor.cores = 1
  spark.executor.memory = "1g"
}

input {
 kudu{
   kudu_master="newcdh01:7051,newcdh02:7051,newcdh04:7051"
   kudu_table="impala::ukudu.k_tag_sb"
   result_table_name="kudu_k_tab_sb_source"
 }
}

filter {
}

output {

 clickhouse {
    source_table_name="kudu_k_tab_sb_source"
    host = "newcdh04:8123"
    clickhouse.socket_timeout = 50000
    database = "test"
    table = "k_tag_sb1"
    # fields = ["cust_no","tag_code","update_datetime"]
    username = "default"
    password = "admin"
    bulk_size = 20000
 }
}
```

### Running Command

```shell
/opt/seatunnel-1.5.5/bin/start-seatunnel.sh --master local[3] --deploy-mode client --config /opt/seatunnel-1.5.5/config/kudu2ch.batch.all.conf
```

### Error Exception

```log
2021-12-22 15:23:47 ERROR TaskSetManager:70 - Task 2 in stage 0.0 failed 1 times; aborting job
Exception in thread "main" java.lang.Exception: org.apache.spark.SparkException: Job aborted due to stage failure: Task 2 in stage 0.0 failed 1 times, most recent failure: Lost task 2.0 in stage 0.0 (TID 2, localhost, executor driver): java.lang.ClassCastException: java.sql.Timestamp cannot be cast to java.lang.String
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse.renderBaseTypeStatement(Clickhouse.scala:351)
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse.io$github$interestinglab$waterdrop$output$batch$Clickhouse$$renderStatementEntry(Clickhouse.scala:373)
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse$$anonfun$io$github$interestinglab$waterdrop$output$batch$Clickhouse$$renderStatement$1.apply$mcVI$sp(Clickhouse.scala:403)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse.io$github$interestinglab$waterdrop$output$batch$Clickhouse$$renderStatement(Clickhouse.scala:391)
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse$$anonfun$process$2.apply(Clickhouse.scala:187)
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse$$anonfun$process$2.apply(Clickhouse.scala:162)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:935)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:935)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:109)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

### Flink or Spark Version

spark-2.3.2-bin-hadoop2.6

### Java or Scala Version

java 1.8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by RickyHuo** [comment]
https://interestinglab.github.io/seatunnel-docs/#/zh-cn/v1/configuration/output-plugins/Clickhouse?id=clickhouse%e7%b1%bb%e5%9e%8b%e5%af%b9%e7%85%a7%e8%a1%a8

@Shmilyqjj Timestamp type should convert to String before output

**Comment by xtr1993** [comment]
you can convert timestamp to string in your kudu source and please keep source types is the same as sink types @Shmilyqjj

**Comment by Shmilyqjj** [comment]
i add this convert:

filter {
  convert {
    source_field = "update_datetime"
    new_type = "string"
  }
}


same error occured. 

Full config:
spark {
  spark.app.name = "kudu2ch"
  spark.executor.instances = 2
  spark.executor.cores = 1
  spark.executor.memory = "1g"
}

input {
 kudu{
   kudu_master="newcdh01:7051,newcdh02:7051,newcdh04:7051"
   kudu_table="impala::ukudu.k_tag_sb"
   result_table_name="kudu_k_tab_sb_source"
 }
}

filter {
  convert {
    source_field = "update_datetime"
    new_type = "string"
  }
}

output {

 clickhouse {
    source_table_name="kudu_k_tab_sb_source"
    host = "newcdh04:8123"
    clickhouse.socket_timeout = 50000
    database = "test"
    table = "k_tag_sb1"
    fields = ["cust_no","tag_code","update_datetime"]
    username = "default"
    password = "admin"
    bulk_size = 20000
 }
}

Is there something wrong with my config ?

**Comment by RickyHuo** [comment]
Like this:
```
date {
    source_field = "update_datetime"
    target_field = "update_datetime"
    source_time_format = "UNIX"
    target_time_format = "yyyy-MM-dd HH:mm:ss"
}
```

**Comment by Shmilyqjj** [comment]
```config
spark {
  spark.app.name = "kudu2ch"
  spark.executor.instances = 2
  spark.executor.cores = 1
  spark.executor.memory = "1g"
}

input {
 kudu{
   kudu_master="newcdh01:7051,newcdh02:7051,newcdh04:7051"
   kudu_table="impala::ukudu.k_tag_sb"
   result_table_name="kudu_k_tab_sb_source"
 }
}

filter {
  date {
      source_field = "update_datetime"
      target_field = "update_datetime"
      source_time_format = "UNIX"
      target_time_format = "yyyy-MM-dd HH:mm:ss"
  }
}

output {

 clickhouse {
    source_table_name="kudu_k_tab_sb_source"
    host = "newcdh04:8123"
    clickhouse.socket_timeout = 50000
    database = "test"
    table = "k_tag_sb1"
    fields = ["cust_no","tag_code","update_datetime"]
    username = "default"
    password = "admin"
    bulk_size = 20000
 }
}
```

This configuration does not work, and the same error still occurs

**Comment by Shmilyqjj** [comment]
![image](https://user-images.githubusercontent.com/43771567/147120085-2f863a47-c9c6-4a27-b487-2df9b73df98c.png)
![image](https://user-images.githubusercontent.com/43771567/147120208-1ea21f2b-a7ed-47d1-b960-321293bb3e05.png)

**Comment by RickyHuo** [comment]
> ```
> spark {
>   spark.app.name = "kudu2ch"
>   spark.executor.instances = 2
>   spark.executor.cores = 1
>   spark.executor.memory = "1g"
> }
> 
> input {
>  kudu{
>    kudu_master="newcdh01:7051,newcdh02:7051,newcdh04:7051"
>    kudu_table="impala::ukudu.k_tag_sb"
>    result_table_name="kudu_k_tab_sb_source"
>  }
> }
> 
> filter {
>   date {
>       source_field = "update_datetime"
>       target_field = "update_datetime"
>       source_time_format = "UNIX"
>       target_time_format = "yyyy-MM-dd HH:mm:ss"
>   }
> }
> 
> output {
> 
>  clickhouse {
>     source_table_name="kudu_k_tab_sb_source"
>     host = "newcdh04:8123"
>     clickhouse.socket_timeout = 50000
>     database = "test"
>     table = "k_tag_sb1"
>     fields = ["cust_no","tag_code","update_datetime"]
>     username = "default"
>     password = "admin"
>     bulk_size = 20000
>  }
> }
> ```
> 
> This configuration does not work, and the same error still occurs

show me the detail error msg.

**Comment by RickyHuo** [comment]
> ```
> spark {
>   spark.app.name = "kudu2ch"
>   spark.executor.instances = 2
>   spark.executor.cores = 1
>   spark.executor.memory = "1g"
> }
> 
> input {
>  kudu{
>    kudu_master="newcdh01:7051,newcdh02:7051,newcdh04:7051"
>    kudu_table="impala::ukudu.k_tag_sb"
>    result_table_name="kudu_k_tab_sb_source"
>  }
> }
> 
> filter {
>   date {
>       source_field = "update_datetime"
>       target_field = "update_datetime"
>       source_time_format = "UNIX"
>       target_time_format = "yyyy-MM-dd HH:mm:ss"
>   }
> }
> 
> output {
> 
>  clickhouse {
>     source_table_name="kudu_k_tab_sb_source"
>     host = "newcdh04:8123"
>     clickhouse.socket_timeout = 50000
>     database = "test"
>     table = "k_tag_sb1"
>     fields = ["cust_no","tag_code","update_datetime"]
>     username = "default"
>     password = "admin"
>     bulk_size = 20000
>  }
> }
> ```
> 
> This configuration does not work, and the same error still occurs

I just gave a sample, the filter of Date means we should convert the field to the formatted string before output.

I have read the related source code. The only way to convert Timestamp to formatted String is using the filter of SQL.

```
sql {
     sql = "select cust_no, tag_code, date_format(update_datetime, 'yyyy-MM-dd') as update_datetime from kudu_k_tab_sb_source"
}
```

I think this will be fine :)

**Comment by Shmilyqjj** [comment]
```
2021-12-23 14:14:59 ERROR Executor:91 - Exception in task 0.0 in stage 0.0 (TID 0)
java.lang.ClassCastException: java.sql.Timestamp cannot be cast to java.lang.String
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse.renderBaseTypeStatement(Clickhouse.scala:351)
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse.io$github$interestinglab$waterdrop$output$batch$Clickhouse$$renderStatementEntry(Clickhouse.scala:373)
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse$$anonfun$io$github$interestinglab$waterdrop$output$batch$Clickhouse$$renderStatement$1.apply$mcVI$sp(Clickhouse.scala:403)        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse.io$github$interestinglab$waterdrop$output$batch$Clickhouse$$renderStatement(Clickhouse.scala:391)
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse$$anonfun$process$2.apply(Clickhouse.scala:187)
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse$$anonfun$process$2.apply(Clickhouse.scala:162)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:935)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:935)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:109)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2021-12-23 14:14:59 ERROR Executor:91 - Exception in task 2.0 in stage 0.0 (TID 2)
java.lang.ClassCastException: java.sql.Timestamp cannot be cast to java.lang.String
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse.renderBaseTypeStatement(Clickhouse.scala:351)
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse.io$github$interestinglab$waterdrop$output$batch$Clickhouse$$renderStatementEntry(Clickhouse.scala:373)
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse$$anonfun$io$github$interestinglab$waterdrop$output$batch$Clickhouse$$renderStatement$1.apply$mcVI$sp(Clickhouse.scala:403)        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse.io$github$interestinglab$waterdrop$output$batch$Clickhouse$$renderStatement(Clickhouse.scala:391)
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse$$anonfun$process$2.apply(Clickhouse.scala:187)
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse$$anonfun$process$2.apply(Clickhouse.scala:162)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:935)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:935)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:109)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2021-12-23 14:14:59 ERROR TaskSetManager:70 - Task 0 in stage 0.0 failed 1 times; aborting job
Exception in thread "main" java.lang.Exception: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost, executor driver): java.lang.ClassCastException: java.sql.Timestamp cannot be cast to java.lang.String
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse.renderBaseTypeStatement(Clickhouse.scala:351)
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse.io$github$interestinglab$waterdrop$output$batch$Clickhouse$$renderStatementEntry(Clickhouse.scala:373)
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse$$anonfun$io$github$interestinglab$waterdrop$output$batch$Clickhouse$$renderStatement$1.apply$mcVI$sp(Clickhouse.scala:403)        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse.io$github$interestinglab$waterdrop$output$batch$Clickhouse$$renderStatement(Clickhouse.scala:391)
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse$$anonfun$process$2.apply(Clickhouse.scala:187)
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse$$anonfun$process$2.apply(Clickhouse.scala:162)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:935)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:935)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:109)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
        at io.github.interestinglab.waterdrop.Waterdrop$.main(Waterdrop.scala:43)
        at io.github.interestinglab.waterdrop.Waterdrop.main(Waterdrop.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost, executor driver): java.lang.ClassCastException: java.sql.Timestamp cannot be cast to java.lang.String
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse.renderBaseTypeStatement(Clickhouse.scala:351)
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse.io$github$interestinglab$waterdrop$output$batch$Clickhouse$$renderStatementEntry(Clickhouse.scala:373)
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse$$anonfun$io$github$interestinglab$waterdrop$output$batch$Clickhouse$$renderStatement$1.apply$mcVI$sp(Clickhouse.scala:403)        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse.io$github$interestinglab$waterdrop$output$batch$Clickhouse$$renderStatement(Clickhouse.scala:391)
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse$$anonfun$process$2.apply(Clickhouse.scala:187)
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse$$anonfun$process$2.apply(Clickhouse.scala:162)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:935)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:935)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:109)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
        at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1651)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1639)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1638)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1638)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:831)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:831)
        at scala.Option.foreach(Option.scala:257)
        at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:831)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1872)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1821)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1810)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
        at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:642)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2034)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2055)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2074)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2099)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:935)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:933)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
        at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:933)
        at org.apache.spark.sql.Dataset$$anonfun$foreachPartition$1.apply$mcV$sp(Dataset.scala:2680)
        at org.apache.spark.sql.Dataset$$anonfun$foreachPartition$1.apply(Dataset.scala:2680)
        at org.apache.spark.sql.Dataset$$anonfun$foreachPartition$1.apply(Dataset.scala:2680)
        at org.apache.spark.sql.Dataset$$anonfun$withNewRDDExecutionId$1.apply(Dataset.scala:3244)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:77)
        at org.apache.spark.sql.Dataset.withNewRDDExecutionId(Dataset.scala:3240)
        at org.apache.spark.sql.Dataset.foreachPartition(Dataset.scala:2679)
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse.process(Clickhouse.scala:162)
        at io.github.interestinglab.waterdrop.Waterdrop$.outputProcess(Waterdrop.scala:251)
        at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$batchProcessing$2.apply(Waterdrop.scala:215)
        at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$batchProcessing$2.apply(Waterdrop.scala:214)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at io.github.interestinglab.waterdrop.Waterdrop$.batchProcessing(Waterdrop.scala:214)
        at io.github.interestinglab.waterdrop.Waterdrop$.io$github$interestinglab$waterdrop$Waterdrop$$entrypoint(Waterdrop.scala:120)
        at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply$mcV$sp(Waterdrop.scala:38)
        at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply(Waterdrop.scala:38)
        at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply(Waterdrop.scala:38)
        at scala.util.Try$.apply(Try.scala:192)
        at io.github.interestinglab.waterdrop.Waterdrop$.main(Waterdrop.scala:38)
        ... 11 more
Caused by: java.lang.ClassCastException: java.sql.Timestamp cannot be cast to java.lang.String
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse.renderBaseTypeStatement(Clickhouse.scala:351)
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse.io$github$interestinglab$waterdrop$output$batch$Clickhouse$$renderStatementEntry(Clickhouse.scala:373)
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse$$anonfun$io$github$interestinglab$waterdrop$output$batch$Clickhouse$$renderStatement$1.apply$mcVI$sp(Clickhouse.scala:403)        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse.io$github$interestinglab$waterdrop$output$batch$Clickhouse$$renderStatement(Clickhouse.scala:391)
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse$$anonfun$process$2.apply(Clickhouse.scala:187)
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse$$anonfun$process$2.apply(Clickhouse.scala:162)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:935)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:935)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:109)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

I also tried this:
```
  sql {
    sql = "select cust_no,tag_code,cast(update_datetime as string) as update_datetime from kudu_k_tab_sb_source",
    table_name = "kudu_k_tab_sb_source"
  }
```
But it still doesn't work.

**Comment by Shmilyqjj** [comment]
大佬帮忙解决了output clickhouse 去掉 source_table_name 解决了

**Comment by Shmilyqjj** [comment]
https://interestinglab.github.io/seatunnel-docs/#/zh-cn/v1/configuration/output-plugin

![image](https://user-images.githubusercontent.com/43771567/147209205-c7335e86-3b72-49b3-82df-eb8bc851c632.png)

**Comment by AshishAAB** [comment]
Is it possible to convert the timestamp types internally to string datatypes ?
I have 100 columns and casting them to string is a very tedious process. 
Any suggestions ?
